### PR TITLE
Added DAY 1

### PR DESCRIPTION
**Pull request by VaarunSinha**
Hi there, added my progress for day 1 please review it.

### CODE REVIEW

**Comment by soham117** [comment]
Where is code @VaarunSinha

**Review by soham117 — CHANGES_REQUESTED** [review]
You need to add code here

**Comment by VaarunSinha** [comment]
Oh Actually it was a workshop, so I coded and recorded it on the spot. That code is not available right now.

**Comment by VaarunSinha** [comment]
When I will attach the recording then you can see what I had written...

**Comment by srbhr** [comment]
@soham117 I'm closing  this PR. It's empty

**Comment by soham117** [comment]
@VaarunSinha kindly add the code files

**Pull request closed without merging**
