### PR TITLE
Fixed: Typo

### PR DESCRIPTION
**Pull request by bobychaudhary**
# 100 days of code

Thanks for your participation in 100 days of code. These 100 days of coding will help you get a nice understanding with hands on approach towards solving problems. Stay determined, stay motivated and happy coding :)

## 📝Please make sure to follow these points

- [ ] Created a separate folder with your name. eg <code>brahmajeet</code>
- [x] Made daily solution file of problem in format. eg <code>DAY-1.py</code>
- [ ] I have uploaded my own solution.
- [ ] My Pull Request title is in format <code>< name > - < day > </code> eg <code>&nbsp;Brahmajeet-day-1</code>
- [x] I will upload ALL MY SOLUTIONS in my folder ONLY.

### Thank you!
Your part is over after your pull request is made. Your Pull Request will be merged soon if approved by maintainers. Happy contributing.

### CODE REVIEW

**Comment by srbhr** [comment]
@bobychaudhary 
Check there is a conflict in the PR
Please make sure that it's resolved.

**Comment by soham117** [comment]
@bobychaudhary Do not change the main Readme.md file. Only contribute in your folder.

**Comment by srbhr** [comment]
@soham117  and @bobychaudhary  there is a minor change in README.md file, I would have suggested an issue or something. But I'll make the change anyway, and then try to merge.

**Comment by srbhr** [comment]
@bobychaudhary  I've done it, please check the mergeability of the branch next time! 😄

**Comment by soham117** [comment]
@srbhr thanks! I will keep in mind

**Pull request merged**
