### PR TITLE
Updated the README.md file. Changed the Discord invite to a never ending invitation.

### PR DESCRIPTION
**Pull request by adityajoshi-08**
…ing invite.

# 100 days of code

Thanks for your participation in 100 days of code. These 100 days of coding will help you get a nice understanding with hands on approach towards solving problems. Stay determined, stay motivated and happy coding :)

## 📝Please make sure to follow these points

- [ ] Created a separate folder with your name. eg <code>brahmajeet</code>
- [ ] Made daily solution file of problem in format. eg <code>DAY-1.py</code>
- [ ] I have uploaded my own solution.
- [ ] My Pull Request title is in format <code>< name > - < day > </code> eg <code>&nbsp;Brahmajeet-day-1</code>
- [ ] I will upload ALL MY SOLUTIONS in my folder ONLY.

### Thank you!
Your part is over after your pull request is made. Your Pull Request will be merged soon if approved by maintainers. Happy contributing.

### CODE REVIEW

**Comment by srbhr** [comment]
@adityajoshi-08  there are two more areas where the link is being used. Can you add 'em there as well?

**Review by srbhr — COMMENTED** [review]
@adityajoshi-08  here

**Comment by srbhr** [comment]
Line 10 and line 18.

**Comment by adityajoshi-08** [comment]
Sure. I will update it.

**Pull request closed without merging**
